api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/config/api_platform']
    graphql:
            enabled: true
            graphiql:
                enabled: true

    resource_class_directories:
      - '%kernel.project_dir%/src/Entity'

