sudo: false

language: php

php:
  - 7.0

before_script:
    - pear install pear/PHP_CodeSniffer
    - phpenv rehash

script:
    - composer install -n
    - phpcs -n --standard=PSR2 src tests
    - phpunit
    - vendor/bin/behat
