imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: elasticsearch_adapter.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    linked_swissbib.elastic_search.hosts: ["localhost"]
    linked_swissbib.context_mapper:
      template_url: 'http://data.swissbib.ch/{type}/context.jsonld'
    linked_swissbib.elasticsearch_params_builder:
      mapped_params:
        single: []
        multi: ['fields']
    linked_swissbib.easyrdf.namespaces:
        bf: 'http://bibframe.org/vocab/'
        hydra: 'http://www.w3.org/ns/hydra/core#'

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    templating:
        engines: ['twig']
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Nelmio CORS
nelmio_cors:
    defaults:
        allow_origin:   ["%cors_allow_origin%"]
        allow_methods:  ["GET"]
        allow_headers:  ["content-type", "authorization"]
        expose_headers: ["link"]
        max_age:        3600
    paths:
        '^/': ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

#API Platform
api_platform:
    title: "Linked swissbib API"
    description: "Hypermedia driven REST API for linked bibliographic resources."
    version: "1.0.0"
    formats:
        jsonld: ["application/ld+json"]
        rdfxml: ["application/rdf+xml"]
        turtle: ["text/turtle"]
        ntriples: ["application/n-triples"]
        html: ["text/html"]
    error_formats:
        jsonld: ["application/ld+json"]
        rdfxml: ["application/rdf+xml"]
        turtle: ["text/turtle"]
        ntriples: ["application/n-triples"]
        html: ["text/html"]
    default_operation_path_resolver: 'linked_swissbib.operation_path_resolver.camel_case'
