parameters:
  elasticsearch_adapter.hosts: ['localhost']
  #elasticsearch_adapter.hosts: ['sb-s2.swissbib.unibas.ch:8080']
  elasticsearch_adapter.templates:
    search:
      index: 'testsb'
      type: 'bibliographicResource, document, item, organization, person, work'
      query:
        multi_match:
          query: '{q}'
          fields: '{fields}'

    empty:
      index: 'testsb'
      type: '{type}'

    id:
      index: 'testsb'
      type: '{type}'
      query:
        ids:
          values: ['{id}']

    collection_fields:
      index: 'testsb'
      type: '{type}'
      size: 20
      query:
        multi_match:
          query: '{q}'
          fields: '{fields}'

    collection_document:
      index: 'testsb'
      type: 'document'
      size: 20
      query:
        multi_match:
          query: '{q}'
          fields: 'bf:local,dct:contributor'

    collection_bibliographicresource:
      index: 'testsb'
      type: 'bibliographicResource'
      size: 20
      query:
        multi_match:
          query: '{q}'
          fields: 'dct:title'

    collection_item:
      index: 'testsb'
      type: 'item'
      size: 20
      query:
        multi_match:
          query: '{q}'
          fields: 'bf:holdingFor,foaf:page,bibo:owner,bibo:locator,bf:subLocation'

    collection_organisation:
      index: 'testsb'
      type: 'organisation'
      size: 20
      query:
        multi_match:
          query: '{q}'
          fields: 'rdfs:label'

    collection_person:
      index: 'testsb'
      type: 'person'
      size: 20
      query:
        multi_match:
          query: '{q}'
          fields: 'firstName,lastName'
