parameters:
  elasticsearch_adapter.hosts: ['localhost']
  elasticsearch_adapter.templates:
    search:
      index: 'testsb_160426'
      type: ['bibliographicResource', 'document', 'item', 'organization', 'person', 'work']
      query:
        multi_match:
          query: '{q}'
          fields: '{fields}'

    collection_fields:
      index: 'testsb_160426'
      type: '{type}'
      size: 20
      query:
        multi_match:
          query: '{q}'
          fields: '{fields}'
#          type: 'cross_fields'
#          operator: 'and'
#          minimum_should_match: '50%'

    collection_all:
      index: 'testsb_160426'
      type: '{type}'
      size: 20
      query:
        match:
          _all: '{q}'

    empty:
      index: 'testsb_160426'
      type: '{type}'

    id:
      index: 'testsb_160426'
      type: '{type}'
      query:
        ids:
          values: ['{id}']
