parameters:
  elasticsearch_adapter.hosts: ['sb-ues1.swissbib.unibas.ch:8080','sb-ues2.swissbib.unibas.ch:8080','sb-ues3.swissbib.unibas.ch:8080']
#  elasticsearch_adapter.hosts: ['sb-s2.swissbib.unibas.ch:8080']
  elasticsearch_adapter.templates:
#    search:
#      index: 'lsb_20170416'
#      type: 'bibliographicResource, document, item, organization, person, work'
#      query:
#        multi_match:
#          query: '{q}'
#          fields: '{fields}'

    empty:
      index: 'lsb_20170416'
      type: '{type}'
      size: 20

    id:
      index: 'lsb_20170416'
      type: '{type}'
      query:
        ids:
          values: ['{id}']

    collection_fields:
      index: 'lsb_20170416'
      type: '{type}'
      size: 20
      query:
        multi_match:
          query: '{q}'
          fields: '{fields}'

    collection_document:
      index: 'lsb_20170416'
      type: 'document'
      size: 20
      query:
        multi_match:
          query: '{q}'
          fields: 'bf:local,dct:contributor,foaf:primaryTopic'

    collection_bibliographicresource:
      index: 'lsb_20170416'
      type: 'bibliographicResource'
      size: 20
      query:
        multi_match:
          query: '{q}'
          fields: 'dct:title,dct:language,bf:instanceOf,dc:format,bibo:edition,bibo:isbn10,bibo:isbn13,bibo:issn,dbp:originalLanguage,dct:alternative,dct:bibliographicCitation,dct:contributor,dct:hasPart,dct:isPartOf,dct:issued,dct:subject,rdfs:isDefinedBy'

    collection_item:
      index: 'lsb_20170416'
      type: 'item'
      size: 20
      query:
        multi_match:
          query: '{q}'
          fields: 'bf:holdingFor,bf:subLocation,bibo:locator,bibo:owner,foaf:page'

    collection_organisation:
      index: 'lsb_20170416'
      type: 'organisation'
      size: 20
      query:
        multi_match:
          query: '{q}'
          fields: 'rdfs:label'

    collection_person:
      index: 'lsb_20170416'
      type: 'person'
      size: 20
      query:
        multi_match:
          query: '{q}'
          fields: 'dbp:birthYear,dbp:deathYear,foaf:firstName,foaf:lastName,foaf:name,schema:sameAs,rdfs:label,skos:note,dbp:birthPlace,dbp:deathPlace,dbp:birthDate,dbp:deathDate,dbp:genre,dbp:movement,dbp:nationality,dbp:notableWork,dbp:occupation,dbp:thumbnail,dbp:influencedBy,dbp:partner,dbp:pseudonym,dbp:spouse,dbp:influenced,schema:alternateName,schema:familyName,schema:givenName,schema:gender,rdf:type,dbp:abstract'

    collection_work:
          index: 'lsb_20170416'
          type: 'work'
          size: 20
          query:
            multi_match:
              query: '{q}'
              fields: 'bf:hasInstance,dct:contributor,dct:title'
