app:
    resource: '@LinkedSwissbibBundle/Action/'
    type:     'annotation'

api:
    resource: '.'
    type:     'api_platform'


root:
    path: /bibliographicResource/{id}/about
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: redirectdocs
        permanent: true
