app:
    resource: '@LinkedSwissbibBundle/Action/'
    type:     'annotation'

api:
    resource: '.'
    type:     'api_platform'

doc:
    resource: '@ApiPlatformBundle/Resources/config/routing/swagger-ui.xml'
