app:
    resource: '@LinkedSwissbibBundle/Action/'
    type:     'annotation'

#compare: https://api-platform.com/docs/core/getting-started
#Register the routes of your api

api:
    resource: '.'
    type:     'api_platform'


root:
    path: /bibliographicResource/{id}/about
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: redirectdocs
        permanent: true
