# Example config file for the Schema Generator
# Use the following command to regenerate entities:
# bin/schema generate-types src/ app/config/schema.yml

types:

  Book:
    parent: false
    properties:
      name: ~
      description: ~
      author:
        range:       Person
        cardinality: (*..*)
        relationTableName: book_author
      publisher:
        range: Organization
        cardinality: (*..1)
      genre: ~
      datePublished: ~
      illustrator:
        cardinality: (*..*)
        relationTableName: book_illustrator
      isbn: ~
      numberOfPages: ~

  Person:
    parent: false
    properties:
      name: ~
      description: ~
      url: ~
      birthDate: ~
      gender: ~

  Organization:
    parent: false
    properties:
      name: ~
      description: ~
      url: ~

namespaces:
  entity: AppBundle\Entity

annotationGenerators:
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DoctrineOrmAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ConstraintAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ApiPlatformCoreAnnotationGenerator
