# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    linked_swissbib.elasticsearch_client:
        class: Elasticsearch\Client
        factory: ['LinkedSwissbibBundle\Elasticsearch\ElasticsearchClientFactory', createClient]
        arguments: ['%linked_swissbib.elastic_search.hosts%']

    linked_swissbib.elasticsearch_item_data_provider:
        class: 'LinkedSwissbibBundle\DataProvider\ElasticsearchDataProvider'
        tags: [ { name: 'api_platform.item_data_provider', priority: 1 } ]
        arguments: ['@linked_swissbib.elasticsearch_client']

