# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    linked_swissbib.elasticsearch_client:
        class: Elasticsearch\Client
        factory: ['LinkedSwissbibBundle\Elasticsearch\ElasticsearchClientFactory', createClient]
        arguments: ['%linked_swissbib.elastic_search.hosts%']

    linked_swissbib.elasticsearch_item_data_provider:
        class: LinkedSwissbibBundle\DataProvider\ElasticsearchDataProvider
        tags: [ { name: 'api_platform.item_data_provider', priority: 1 } ]
        arguments: ['@linked_swissbib.elasticsearch_client', '@linked_swissbib.entity_simple_entity_builder' ,'@linked_swissbib.elasticsearch_context_mapper']

    linked_swissbib.elasticsearch_context_mapper:
        class: LinkedSwissbibBundle\Elasticsearch\ElasticsearchContextMapper
        arguments: ['@linked_swissbib.cache']

    linked_swissbib.naming.resource_path_naming_strategy.camel_case:
        class: LinkedSwissbibBundle\Naming\CamelCaseResourcePathGenerator

    linked_swissbib.easy_rdf_graph:
        class: EasyRdf_Graph

    linked_swissbib.rdfxml_encoder:
        class: LinkedSwissbibBundle\Serializer\Encoder\RdfxmlEncoder
        tags: [ { name: serializer.encoder } ]
        arguments: ['@linked_swissbib.easy_rdf_graph']

    linked_swissbib.cache:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: ['%kernel.cache_dir%']

    linked_swissbib.entity_simple_entity_builder:
        class: LinkedSwissbibBundle\Entity\SimpleEntityBuilder
        arguments: ['@logger']

    linked_swissbib.serializer.normalizer.item:
        class: LinkedSwissbibBundle\Serializer\ItemNormalizer
        decorates: api_platform.jsonld.normalizer.item
        arguments: ['@linked_swissbib.serializer.normalizer.item.inner', '@api_platform.resource_class_resolver']
        tags: [ { name: 'serializer.normalizer', priority: 12 } ]
